FROM nginx@sha256:728f60fda76b3750259ff588f3c1fce07a59eaf6e08713f1441de50e91d221e8

COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/localhost.crt /etc/ssl/ssl.crt
COPY ssl/localhost.key /etc/ssl/ssl.key