version: "3"

services:
  db:
    image: postgres@sha256:4ba3b78788bb284687376b9c1e0565b245375ddee0fe14cef25e315b6bd88b1a
    restart: always
    environment:
      POSTGRES_PASSWORD: jkbn
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  idp:
    image: quay.io/keycloak/keycloak@sha256:b4841a7b8401fd209bfcddf10773cdfa7c7cfde4bf7e87780663226be5587ee2
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
  ingress:
    image: nginx@sha256:728f60fda76b3750259ff588f3c1fce07a59eaf6e08713f1441de50e91d221e8
    restart: always
#  api:
#    image: scratch
#    restart: always
#  frontend:
#    image: scratch
#    restart: always
#  agent:
#    image: scratch
#    restart: always


volumes:
  pg_data:
